apiVersion: v1
kind: Secret
metadata:
  name: postfix-smtp-secret
  namespace: default
type: Opaque
stringData:
  # Base64 encoding is not required when using stringData
  SMTP_PASSWORD: "your_google_app_password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-smtp-config
  namespace: default
data:
  SMTP_USERNAME: "4468618@gmail.com"
  TARGET_EMAIL: "4468618@gmail.com"
  MYNETWORKS: "127.0.0.0/8, 10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-smtp-relay
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix-smtp-relay
  template:
    metadata:
      labels:
        app: postfix-smtp-relay
    spec:
      containers:
        - name: postfix-smtp-relay
          image: akhaladze/postfix-gmail:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 25
          envFrom:
            - configMapRef:
                name: postfix-smtp-config
          env:
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postfix-smtp-secret
                  key: SMTP_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: postfix-smtp-service
  namespace: default
spec:
  selector:
    app: postfix-smtp-relay
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
  # Change to LoadBalancer or NodePort if access from outside the cluster is needed
  type: ClusterIP
