version: '3.8'

services:
  postfix-relay:
    image: akhaladze/postfix-gmail:v1.0.0
    container_name: postfix-smtp-gmail
    restart: unless-stopped
    ports:
      - "25:25"
    env_file:
      - stack.env
